### ISSUE TITLE
Better handle unknown configuration options

### ISSUE THREAD

**Issue by bochecha** [endlessm/azafea#1]
The config system is nice in that it validates the configuration, and specifically the types of the options, hopefully giving administrators good error messages about what failed.

But try it with the following configuration:

```toml
[main]
foo = "bar"
```

And you get a completely mystifying error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mathieu/Projects/endless/azafea/azafea/__main__.py", line 26, in <module>
    sys.exit(args.subcommand(args))
  File "/home/mathieu/Projects/endless/azafea/azafea/cli.py", line 120, in do_print_config
    config = Config.from_file(args.config)
  File "/home/mathieu/Projects/endless/azafea/azafea/config/__init__.py", line 161, in from_file
    main = Main(**overrides.get('main', {}))
TypeError: __init__() got an unexpected keyword argument 'foo'
```

We should be able to do better.

This is possible with a simple typo, for example:

```toml
[postgresql]
pasword = "super secret"
```

Such a typo would be hard to spot by someone stressfully trying to deploy Azafea with a deadline, and we can't just ignore the unknown option because then the default password would be used.

So we should completely abort on such cases (as is the case currently), but with a proper error message.

**Comment by bochecha** [comment]
This is slightly better with the current master:

```
[ERROR] azafea.cli: Invalid configuration:
* postgresql: __init__() got an unexpected keyword argument 'pasword'
```

Still unclear, but at least that's not a scary traceback any more. :+1:
