### ISSUE TITLE
Better handle missing configuration options

### ISSUE THREAD

**Issue by bochecha** [endlessm/azafea#2]
The config system is nice in that it validates the configuration, and specifically the types of the options, hopefully giving administrators good error messages about what failed.

But try it with the following configuration:

```toml
[queues.te]
```

And you get a completely mystifying error:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mathieu/Projects/endless/azafea/azafea/__main__.py", line 26, in <module>
    sys.exit(args.subcommand(args))
  File "/home/mathieu/Projects/endless/azafea/azafea/cli.py", line 120, in do_print_config
    config = Config.from_file(args.config)
  File "/home/mathieu/Projects/endless/azafea/azafea/config/__init__.py", line 177, in from_file
    queues[name] = Queue(**queue_options)
TypeError: __init__() missing 1 required positional argument: 'handler'
```

We should be able to do better.

**Comment by bochecha** [comment]
This is slightly better with the current master:

```
[ERROR] azafea.cli: Invalid configuration:
* queues.te: __init__() missing 1 required positional argument: 'handler'
```

Still unclear, but at least that's not a scary traceback any more. +1
